export const EVENTS = {
    OPEN_POPUP_WINDOW: 'OPEN_POPUP_WINDOW',
    SIGN_STATE_TRANSITION: 'SIGN_STATE_TRANSITION',
}

export const MESSAGING_TIMEOUT = 60 * 1000
export const POPUP_WINDOW_WIDTH = 250
export const POPUP_WINDOW_HEIGHT = 500
