export enum MessagingMethods {
  // private
  GET_STATUS = 'GET_STATUS',
  CHECK_PASSWORD = 'CHECK_PASSWORD',
  SETUP_PASSWORD = 'SETUP_PASSWORD',
  CREATE_IDENTITY = 'CREATE_IDENTITY',
  GET_IDENTITIES = 'GET_IDENTITIES',
  GET_CURRENT_IDENTITY = 'GET_CURRENT_IDENTITY',
  APPROVE_STATE_TRANSITION = 'APPROVE_STATE_TRANSITION',
  GET_STATE_TRANSITION = 'GET_STATE_TRANSITION',
  REJECT_STATE_TRANSITION = 'REJECT_STATE_TRANSITION',
  CREATE_WALLET = 'CREATE_WALLET',
  SWITCH_WALLET = 'SWITCH_WALLET',
  SWITCH_IDENTITY = 'SWITCH_IDENTITY',
  GET_APP_CONNECT = 'GET_APP_CONNECT',
  APPROVE_APP_CONNECT = 'APPROVE_APP_CONNECT',
  REJECT_APP_CONNECT = 'REJECT_APP_CONNECT',
  FETCH_IDENTITY_BY_PUBLIC_KEY_HASH = 'FETCH_IDENTITY_BY_PUBLIC_KEY_HASH',

  // public
  CONNECT_APP = 'CONNECT_APP',
  REQUEST_STATE_TRANSITION_APPROVAL = 'REQUEST_STATE_TRANSITION_APPROVAL',
  GET_AVAILABLE_IDENTITIES = 'GET_AVAILABLE_IDENTITIES',
}
