export enum MessagingMethods {
    CONNECT_APP = 'CONNECT_APP',
    IMPORT_IDENTITY = 'IMPORT_IDENTITY',
    GET_CURRENT_IDENTITY = 'GET_CURRENT_IDENTITY',
    GET_AVAILABLE_IDENTITIES = 'GET_AVAILABLE_IDENTITIES',
    REQUEST_STATE_TRANSITION_APPROVAL = 'REQUEST_STATE_TRANSITION_APPROVAL',
    GET_STATE_TRANSITION = 'GET_STATE_TRANSITION',
    REJECT_STATE_TRANSITION = 'REJECT_STATE_TRANSITION',
    APPROVE_STATE_TRANSITION = 'APPROVE_STATE_TRANSITION',
}
