export enum MessagingMethods {
    // private
    GET_STATUS = 'GET_STATUS',
    CHECK_PASSWORD = 'CHECK_PASSWORD',
    SETUP_PASSWORD = 'SETUP_PASSWORD',
    CREATE_IDENTITY = 'CREATE_IDENTITY',
    GET_AVAILABLE_IDENTITIES = 'GET_AVAILABLE_IDENTITIES',
    GET_CURRENT_IDENTITY = 'GET_CURRENT_IDENTITY',
    APPROVE_STATE_TRANSITION = 'APPROVE_STATE_TRANSITION',
    GET_STATE_TRANSITION = 'GET_STATE_TRANSITION',
    REJECT_STATE_TRANSITION = 'REJECT_STATE_TRANSITION',
    CREATE_WALLET = 'CREATE_WALLET',
    SWITCH_WALLET = 'SWITCH_WALLET',
    SWITCH_IDENTITY = 'SWITCH_IDENTITY',

    // public
    CONNECT_APP = 'CONNECT_APP',
    REQUEST_STATE_TRANSITION_APPROVAL = 'REQUEST_STATE_TRANSITION_APPROVAL',
}
