name: Publish package to NPM
on:
  release:
    types: [published]
jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build

      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: dist
          zipFilePath: release/dash-platform-extension_${{ github.event.release.tag_name }}_chrome.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/dash-platform-extension_${{ github.event.release.tag_name }}_chrome.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
