name: Publish package to NPM
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build

      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: dist
          zipFilePath: release/dash-platform-extension_${{ github.ref }}_chrome.zip

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: release/dash-platform-extension_${{ github.ref }}_chrome.zip
